src/com/powertuple/intellij/haskell/HaskellParserDefinition.scala, src/com/powertuple/intellij/haskell/highlighter/HaskellSyntaxHighlighter.scala
Remove styles for whitespace, and makes Default inherit from the non-green Comma style. See issue #24.
=> Fix green whitespace

src/main/scala/intellij/haskell/code/HaskellCompletionContributor.scala
Fix #35 
@rikvdkleij 
btw, i think we should ignore `intellij-haskell/intellij-haskell.iml` cause contributors will use any version of IDEA. for me, i currently use IDEA 15.0.2 Community Edition, so i have to checkout this file before commit some changes.
but `intellij-haskell/intellij-haskell.iml` is really important in current plugin dev work flow, so maybe a `intellij-haskell/intellij-haskell.iml.example` should be tracked and ignore the real `.iml` file.
=> omit code completion in string literal

src/main/scala/intellij/haskell/external/component/NameInfoComponent.scala
The issue was with different formating of the output of `:info` on windows.
On linux:
`dropWhile :: (a -> Bool) -> [a] -> [a] 	-- Defined in ‘GHC.List’`
On windows:
```dropWhile :: (a -> Bool) -> [a] -> [a] 	-- Defined in `GHC.List'```
(note the ticks)
=> Fix parsing issues on windows

src/main/scala/intellij/haskell/sdk/HaskellSdkType.scala
@rikvdkleij I think it is better to show Stack version explicitly in `project` view.
=> Show Stack SDK Version

src/main/scala/intellij/haskell/action/CreateHaskellFileAction.scala, src/main/scala/intellij/haskell/util/HaskellFileUtil.scala
Mentioned at #69.
* Adding module prefix when creating files in nested packages.
=> Add module prefix when create new Haskell module

intellij-haskell/META-INF/plugin.xml, src/main/scala/intellij/haskell/psi/HaskellReferenceContributor.scala, src/main/scala/intellij/haskell/refactor/HaskellRenameFileProcessor.scala, src/main/scala/intellij/haskell/refactor/HaskellRenameVariableProcessor.scala
* Renaming a file should rename the module name without the module prefix.
1. Currently, I just ignore the references between `HS_MODID` and Haskell files [here](https://github.com/zjhmale/intellij-haskell/blob/bc9582666cccee8f9e538dd070cc99018fb36512/src/main/scala/intellij/haskell/psi/HaskellReferenceContributor.scala#L33) in order to make sure the renaming file action work as expected, but we can not rename module name anymore.
So maybe the references of `HS_MODID`  [here](https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/navigation/HaskellReference.scala#L41) can be improved? In the old way, renaming a file and renaming module name will override the module prefix.
2. Rename package name should also rename the module prefix, maybe …
=> Sync module name when rename file

intellij-haskell/META-INF/plugin.xml
Related with #70.
@rikvdkleij Now the template in Settings/CodeTemplates is the same as the that is used when creating a new file.
=> Fix internalFileTemplate

src/main/scala/intellij/haskell/annotator/HaskellAnnotator.scala
@rikvdkleij Address issues of redundant import intention.
BTW, I still don't understand, why we only need ```[‘`](.+)[’']``` instead of ```[‘'`](.+)[’'`]``` in `DefinedButNotUsedPattern`. Do we miss a quote ```[']``` on the left and a quasi quote ```[`]``` on the right?
=> Improve redundant import intention

src/main/scala/intellij/haskell/cabal/lang/parser/CabalParser.scala
Resolve eta-expansion of zero-argument method warnings which introduce since [scala2.12](http://www.scala-lang.org/news/2.12.0).
>Eta-expansion (conversion of a method to a function value) of zero-args methods has been deprecated, as this can lead to surprising behavior (#5327).
And currently I believe `() => foo()` is the safest way to invoke 0 argument method instead of `foo _`.
Related to #81.
=> Resolve compiler warning

src/main/scala/intellij/haskell/action/HindentFormatAction.scala, src/main/scala/intellij/haskell/action/StylishHaskellFormatAction.scala, src/main/scala/intellij/haskell/annotator/HaskellAnnotator.scala, src/main/scala/intellij/haskell/external/commandLine/CommandLine.scala, src/main/scala/intellij/haskell/external/component/HLintComponent.scala, src/main/scala/intellij/haskell/external/component/HaskellDocumentationProvider.scala, src/main/scala/intellij/haskell/settings/HaskellSettingsState.scala
IntelliJ uses HTML syntax internally instead of markdown syntax, so maybe it is better to use HTML highlight tag in balloon notifications.
=> Use html highlight tag

src/main/scala/intellij/haskell/external/component/HLintComponent.scala, src/main/scala/intellij/haskell/external/component/HaskellDocumentationProvider.scala
Currently if stack can not find an executable it will produce the stderr
>Executable named xxx not found on path: ...
So maybe it is better to check executables using exit code.
@rikvdkleij BTW, if I remove hlint from the path, and I can not locate the hlint executable using `which hlint` any more, `stack exec -- hlint` still works fine, can you explain the details under the hood?
=> Use exit code to check executables

src/main/scala/intellij/haskell/external/component/CabalConfigComponent.scala
Fix issue mentioned in gitter.
But @NightRa originally post this issue with
>CabalConfigComponent.getResolverFromLocalPkgdb, stack 1.3.2 returns "C:\Users\Ilan\Programming\Haskell-Playground.stack-work\install\ef7d292a\pkgdb", which contains no version.
The local pkgdb path neither contains resolver name or ghc version, in what scenario it will only contain a hash value?
=> Download Nightly Cabal Config File

src/main/scala/intellij/haskell/action/CreateHaskellFileAction.scala
Based on #70 and #74.
* Add module prefix in `MODULE_DECLARATION` for new created Haskell modules.
* Support creating Haskell file with module prefixes. e.g. you can type `xxx.xxx.xxx` in the `New Haskell File` dialog.
* This time, you can create Haskell file everywhere, there will no issues again which discussed at #74.
=> Improve create Haskell file action

src/main/scala/intellij/haskell/external/component/HoogleComponent.scala
Fixes #157.
Actually, maybe this is a hoogle upstream issue because it will treat these output below as stderr.
So we should avoid it in order to make sure it will not introduce any confusions for users.
=> Eliminate hoogle error log

src/main/scala/intellij/haskell/module/HaskellModuleBuilder.scala
Since #135 is taking redownloading library sources into consideration, so remove the library root directory and download all library sources is not a good idea anymore, it will cost user extra time to wait for the downloading process if there is a bunch of dependencies.
This PR handles two things
* Delete library sources which are no longer as dependencies of the project.
* Just download library sources which are not downloaded before.
=> Optimize downloading library sources

intellij-haskell/META-INF/plugin.xml
Behavior of `Ctrl+Alt+U` hotkey was the same as the `Ctrl+Alt+;` - `hindent` was called anyway before `stylish-haskell`. It was due to bug (probably copy-paste error) in `plugin.xml`. This PR fixes behavior of `Ctrl+Alt+U` hotkey by calling appropriate format action.
=> Fix stylish-haskell only format action

intellij-haskell/META-INF/plugin.xml, src/main/scala/intellij/haskell/action/ShowTypeAction.scala, src/main/scala/intellij/haskell/action/ShowTypeStickyAction.scala, src/main/scala/intellij/haskell/psi/HaskellPsiUtil.scala, src/main/scala/intellij/haskell/util/HaskellEditorUtil.scala
This is my attempt to add "sticky" Show Type Info as discussed in #199. Feel free to change the name. I didn't know what else to call it.
I tried to re-use already existing helper methods as much as I could, but I might have missed some. Particularly the whitespace handling was a little tricky because those nodes are on a different branch of the tree, so I had to "re-enter" the expression. I suspect there's a better way to do that, but I couldn't find anything to help me with that.
I'm sure this can be improved over time with better heuristics, but I kept the initial implementation simple for now.
=> Add "sticky" type info action

src/main/scala/intellij/haskell/external/component/HoogleComponent.scala
Hoogle outputs excessive newlines in many cases (3 or more). For example, if you run `hoogle -i catMaybes` you should see what I'm referring to.
I think this occurs because Hoogle cleans up html tags, but doesn't touch up all the newlines that this leaves behind?
Anyway, here is a quick fix for that.
Also, `getStdout` is NotNull, so I removed the unnecessary null check.
=> Clean Hoogle output for documentation

src/main/resources/ghci/8.2.1.ghci, src/main/resources/ghci/default.ghci, src/main/scala/intellij/haskell/runconfig/console/HaskellConsoleState.scala, src/main/scala/intellij/haskell/runconfig/console/HaskellConsoleView.scala
Fixes #212 
Some notes about the implementation so far:
- `prompt2` looks like it was renamed to `prompt-cont` in GHC 8.2.1. To get rid of that `Some flags have not been recognized: prompt2,` warning, I guess I would need to create 2 separate GHCi config files.
- Rather than use a GHCi config file, it would be nice if I could set them with plain CLI flags (or environment variables)... but I couldn't find any such options in GHCi. It looks like the only choices are to use a config file, or send each command one by one after the REPL starts (like ":set +m", ":set prompt ...", and so on).
After some thinking, I'm actually thinking the latter is better, because that way I only override the relevant options and don't mess with any other custom settings a user has in their `.ghci` file. Because …
=> Add multi-line REPL support

README.md
This PR adds several sentences noting how `hindent` takes its options from internal IntelliJ settings.
=> Add documentation on how hindent is used

build.sbt, src/main/scala/intellij/haskell/GlobalInfo.scala
Implements #315. This will prefer and keep using an existing `~/.intellij-haskell` so that existing installations will not be affected. First run in a clean system will choose `cacheDir` using [soc/directories-jvm](https://github.com/soc/directories-jvm#basedirectories).
I can add a note to README if you think it’s worth mentioning?
=> Use OS-specific directory for peristent data

intellij-haskell/META-INF/plugin.xml, src/main/scala/intellij/haskell/highlighter/HaskellSoftKeywordsAnnotator.scala
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2609634/intellij-haskell.zip)
Addressing comments from https://github.com/rikvdkleij/intellij-haskell/issues/329#issuecomment-441117025
Highlighting `as`, `hiding` and `qualified` as keywords.
=> Add soft keyword annotator

intellij-haskell/META-INF/plugin.xml, src/main/resources/dictionary/haskell.dic, src/main/scala/intellij/haskell/highlighter/HaskellColorSettingsPage.scala, src/main/scala/intellij/haskell/highlighter/HaskellSoftKeywordsAnnotator.scala, src/main/scala/intellij/haskell/highlighter/HaskellSyntaxHighlighter.scala
=> Update pragma/function name highlight and color settings page, move config page

gen/intellij/haskell/psi/HaskellTextLiteral.java, intellij-haskell/META-INF/plugin.xml, src/main/scala/intellij/haskell/alex/lang/psi/impl/AlexElementImpl.scala, src/main/scala/intellij/haskell/alex/lang/psi/impl/AlexHaskellCodeInjectionHost.scala, src/main/scala/intellij/haskell/alex/lang/psi/impl/AlexIdMixin.scala, src/main/scala/intellij/haskell/haskell.bnf, src/main/scala/intellij/haskell/highlighter/HaskellHighlightingAnnotator.scala, src/main/scala/intellij/haskell/psi/impl/HaskellCompositeElementImpl.scala, src/main/scala/intellij/haskell/psi/impl/HaskellStringEscaper.java, src/main/scala/intellij/haskell/psi/impl/HaskellStringLiteralElementImpl.scala, src/main/scala/intellij/haskell/psi/impl/HaskellStringLiteralManipulator.scala
=> Support string literal language injection

README.md
As per https://github.com/rikvdkleij/intellij-haskell/issues/417, it looks like the `/8258` part is no longer necessary. Builds get stuck on `beta43` otherwise
=> Update alpha repo url

src/main/scala/intellij/haskell/external/component/HoogleComponent.scala
Addressing #436 by adding is:exact to the arguments sent to the hoogle CLI to avoid showing the documentation for (++) when requesting the documentation for (+).
The popup now shows:
> ```
> No documentation found
> ```
> -----
> GHC.Num    -- No type info available
> 
> -----
=> Have (+) show correct quick documentation (none). Fix issue #436.

src/main/scala/intellij/haskell/GlobalInfo.scala, src/main/scala/intellij/haskell/HTool.scala, src/main/scala/intellij/haskell/action/HindentReformatAction.scala, src/main/scala/intellij/haskell/action/StylishHaskellReformatAction.scala, src/main/scala/intellij/haskell/external/component/HLintComponent.scala, src/main/scala/intellij/haskell/external/component/HoogleComponent.scala, src/main/scala/intellij/haskell/external/component/StackProjectManager.scala, src/main/scala/intellij/haskell/external/execution/StackCommandLine.scala, src/main/scala/intellij/haskell/settings/HaskellConfigurable.scala, src/main/scala/intellij/haskell/settings/HaskellSettingsPersistentStateComponent.java, src/main/scala/intellij/haskell/settings/HaskellSettingsState.scala
Fixes https://github.com/rikvdkleij/intellij-haskell/issues/446 by adding settings:
- a checkbox for _Build tools using system GHC_
- a text box for _Hindent path_
- a text box for _Hlint path_
- a text box for _Hoogle path_
- a text box for _Stylish Haskell path_
=> Make `system-ghc` and tool paths configurable

src/main/scala/intellij/haskell/util/HaskellProjectUtil.scala
In some of our projects, we had issues opening haskell projects that have the following structure:
```
.
├── .idea // <- contains the .iml file here
├── Setup.hs
├── dir1
│   └── task1
│       ├── Task.hs
│       ├── Test.hs
│       └── task.md
├── haske89.cabal
├── stack.yaml
```
And whenever `HaskellProjectUtil.getModuleDir` in https://github.com/i-walker/intellij-haskell/blob/382179707700d835346ad271cc1a4f67d69629f5/src/main/scala/intellij/haskell/external/repl/StackReplsManager.scala#L72. the list will be empty as the Path will be the `.idea` directory. 
The project gets loaded as is, but the user experience is not nice seeing this every time.
I am open for Feedback.
=> Can't find cabal file

src/main/scala/intellij/haskell/external/execution/CommandLine.scala, src/main/scala/intellij/haskell/external/execution/StackCommandLine.scala
This will use IDEA-backed ANSI decoder to decode the escape sequences, so `[0m` won't be shown to the user.
Closes #585.
=> Use ANSI escape decoder for command-line output

README.md
This change got mainly performed by Grammarly, a Grammar checker that is available for Android, as a web service and Browser plugin. 
I double-checked it manually to avoid possible issues.
=> Grammar check by Grammarly and me :)

src/main/scala/intellij/haskell/editor/HaskellCompletionContributor.scala, src/main/scala/intellij/haskell/external/component/HaskellDocumentationProvider.scala, src/main/scala/intellij/haskell/external/component/NameInfoComponent.scala, src/main/scala/intellij/haskell/navigation/HaskellReference.scala
Fixes issue #638
Preview:
Using `originalElement` in
```scala
getQuickNavigateInfo(element: PsiElement, originalElement: PsiElement)
```
does not work because it seems to be `PsiWhiteSpace` when using code completion, so I changed it to always use `element`. I am not sure if this breaks other features.
Sometimes I can not navigate through the options using the arrow keys on my keyboard, only using my mouse. I don't know why this is happening.
The documention lookup is only done when pressing CTRL+Q so it should not affect the responsiveness.
=> Documentation in code completion

src/main/scala/intellij/haskell/sdk/HaskellSdkType.scala
It's the recommended path by stack https://docs.haskellstack.org/en/stable/install_and_upgrade/#path
=> Add default sdk home path for windows
