- src/main/scala/intellij/haskell/external/repl/StackReplProcess.scala
Hi!
This PR fixes process interaction on Windows & provides a more stable check for correct output from the repl.
Do you have some chat where we can interact?
> Fix process interaction on Windows & more stable check for correct output

- src/main/scala/intellij/haskell/intention/AddParensIntention.scala
- src/main/scala/intellij/haskell/psi/HaskellElementFactory.scala
- src/main/scala/intellij/haskell/psi/HaskellPsiUtil.scala
Refactor https://github.com/rikvdkleij/intellij-haskell/pull/59.
Btw, expand selection and shrink selection works great 👍 .
> Refactor using HaskellElementFactory

- src/main/scala/intellij/haskell/intention/AddParensIntention.scala
- src/main/scala/intellij/haskell/intention/RemoveParensIntention.scala
- src/main/scala/intellij/haskell/psi/HaskellPsiUtil.scala
> Using Option monad to get rid of NPE

- src/main/scala/intellij/haskell/annotator/HaskellAnnotator.scala
- src/main/scala/intellij/haskell/psi/HaskellElementCondition.scala
- src/main/scala/intellij/haskell/psi/HaskellElementFactory.scala
- src/main/scala/intellij/haskell/psi/HaskellPsiUtil.scala
> [INTENTION] Import alone instances

- src/main/scala/intellij/haskell/annotator/HaskellAnnotator.scala
> [INTENTION] Redundant import

- intellij-haskell/META-INF/plugin.xml
Trying to make the `extensions` part of plugin.xml more neat and readable.
> Wrap up plugin.xml

- intellij-haskell/META-INF/plugin.xml
- src/main/scala/intellij/haskell/spellchecker/CabalSpellcheckingStrategy.scala
> Add Cabal file spellchecker

- README.md
- src/main/scala/intellij/haskell/module/HaskellModuleBuilder.scala
> Make ideaHaskellLib as hidden directory

- intellij-haskell/META-INF/plugin.xml
> Add action group

- intellij-haskell/META-INF/plugin.xml
@rikvdkleij Sorry, I just forgot to rebase after #119 was merged 😅
> Fix action group icon

- intellij-haskell/META-INF/plugin.xml
- src/main/scala/intellij/haskell/action/AboutAction.scala
- src/main/scala/intellij/haskell/action/HindentFormatAction.scala
- src/main/scala/intellij/haskell/action/StylishHaskellFormatAction.scala
- src/main/scala/intellij/haskell/settings/HaskellSettingsState.scala
* Originally if I click the `About Haskell Project` button, it will introduce an NPE:
>null
java.lang.IllegalMonitorStateException
at java.lang.Object.notify(Native Method)
at intellij.haskell.HaskellNotificationGroup$.log(HaskellNotificationGroup.scala:104)
at intellij.haskell.HaskellNotificationGroup$.balloonEvent(HaskellNotificationGroup.scala:98)
at intellij.haskell.HaskellNotificationGroup$.logErrorBalloonEvent(HaskellNotificationGroup.scala:70)
at intellij.haskell.settings.HaskellSettingsState$.notifyIfPathIsNotSet(HaskellSettingsState.scala:38)
at intellij.haskell.settings.HaskellSettingsState$.getHindentPath(HaskellSettingsState.scala:26)
at intellij.haskell.action.AboutAction.$anonfun$actionPerformed$1(AboutAction.scala:42)
at …
> Fix about page

- intellij-haskell/META-INF/plugin.xml
I think it is a convention that each word in action name should be capitalized 😄
> Capitalize action name

- src/main/scala/intellij/haskell/action/AboutAction.scala
Fixes issue mentioned at #124, Only bold tool names in OSX.
> Highlight external tool name in about page

- README.md
- src/main/scala/intellij/haskell/HaskellNotificationGroup.scala
- src/main/scala/intellij/haskell/module/StackProjectImportBuilder.scala
* Capitalize word.
* Add missing semicolons.
* I think `Haskell Stack` is neater than `Haskell Stack importer` in project wizard.
> Minor fixes

- src/main/scala/intellij/haskell/module/HaskellModuleBuilder.scala
> Add Libraries to External Libraries tree

- src/main/scala/intellij/haskell/module/HaskellModuleBuilder.scala
Reverts rikvdkleij/intellij-haskell#138
> Revert "Add Libraries to External Libraries tree"

- src/main/scala/intellij/haskell/intention/AddParensIntention.scala
> Fix add paren intention for one character expression

- src/main/scala/intellij/haskell/HaskellNotificationGroup.scala
- src/main/scala/intellij/haskell/annotator/HaskellAnnotator.scala
> Navigate to error location for `LoadProblemInOtherFile`

- src/main/scala/intellij/haskell/action/HaskellFormatAction.scala
- src/main/scala/intellij/haskell/action/HindentFormatAction.scala
- src/main/scala/intellij/haskell/inspection/HLintQuickfix.scala
- src/main/scala/intellij/haskell/util/HaskellFileUtil.scala
Related to #151.
It is better to automatically trigger hindent formatting after applying hlint quick fix 😃
> Reformat using hindent after apply hlint quickfix

- src/main/scala/intellij/haskell/inspection/HLintInspectionTool.scala
> A trade off to handle hlint line breaks

- src/main/scala/intellij/haskell/intention/AddParensIntention.scala
- src/main/scala/intellij/haskell/psi/HaskellPsiUtil.scala
Address the issues discussed at #59.
> Parens intention improvement

- intellij-haskell/META-INF/plugin.xml
- src/main/scala/intellij/haskell/action/AboutAction.scala
- src/main/scala/intellij/haskell/action/RestartStackReplsAction.scala
- src/main/scala/intellij/haskell/external/component/StackProjectManager.scala
- src/main/scala/intellij/haskell/external/component/StackProjectStartupManager.scala
- src/main/scala/intellij/haskell/module/HaskellModuleBuilder.scala
- src/main/scala/intellij/haskell/notification/ConfigFileWatcherNotificationProvider.scala
- src/main/scala/intellij/haskell/sdk/HaskellSdkType.scala
- src/main/scala/intellij/haskell/util/HaskellProjectUtil.scala
> Add config file watcher to restart stack repls

- src/main/scala/intellij/haskell/runconfig/console/HaskellConsoleState.scala
Fixes #229
I kept this minimal, but I suppose it could be made smarter as to not create a temp file each time you start a new REPL (perhaps caching + using tempDirectory with fixed ghci files).
> Use temporary file for ghci-script

- build.sbt
- src/main/scala/intellij/haskell/runconfig/console/HaskellConsoleState.scala
- src/main/scala/intellij/haskell/runconfig/console/HaskellConsoleView.scala
Fixes #239
I built the fix on top of the old code because `ConsoleViewContentType.USER_INPUT` isn't doing what I expected it to.
> Fix execution bug in REPL panel

- src/main/scala/intellij/haskell/sdk/HaskellSdkType.scala
- src/main/scala/intellij/haskell/sdk/HaskellStackVersionValidator.scala
- src/test/scala/intellij/haskell/sdk/HaskellStackVersionValidatorSpec.scala
Closes #299 
This is my very first Scala code so please feel free to any criticism 😄
> fix(stack version): Correctly detect Stack version

- intellij-haskell/META-INF/plugin.xml
- src/main/resources/fileTemplates/internal/Haskell Module.hs.html
- src/main/resources/fileTemplates/internal/Haskell Test Module.hs.ft
- src/main/resources/fileTemplates/internal/Haskell Test Module.hs.html
- src/main/scala/intellij/haskell/action/CreateHaskellFileAction.scala
- src/main/scala/intellij/haskell/testIntegration/CreateHaskellTestAction.scala
- src/main/scala/intellij/haskell/testIntegration/CreateHaskellTestDialog.form
- src/main/scala/intellij/haskell/testIntegration/CreateHaskellTestDialog.java
- src/main/scala/intellij/haskell/testIntegration/HaskellTestCreator.scala
- src/main/scala/intellij/haskell/testIntegration/HaskellTestFinder.scala
I think this is far from perfect, but I've spent enough time trying to figure out the Intellij API...
Please feel free to give any (constructive) criticism on my code, I'm an adept of [Egoless programming](https://blog.codinghorror.com/the-ten-commandments-of-egoless-programming/).
Be it on my Scala writing, Intellij integration, style or anything.
I also made extra effort on documentation since I got quite frustrated with the lack of documentation in Intellij sources 😄 
Cheers
Closes #307
> Feat: Jump from/to test + Create test

- intellij-haskell/META-INF/plugin.xml
- src/main/resources/liveTemplates/Haskell.xml
- src/main/scala/intellij/haskell/editor/HaskellLiveTemplate.scala
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2612207/intellij-haskell.zip)
Will attach screenshots soon
> Add live template contexts and some default live templates

- src/main/scala/intellij/haskell/action/CreateHaskellFileAction.scala
DO NOT MERGE RIGHT NOW.
For testing and discussion.
> Trying to fix #339

- src/main/scala/intellij/haskell/psi/impl/HaskellStringLiteralManipulator.scala
> Fix a bug mentioned in the previous PR

- src/main/resources/liveTemplates/Haskell.xml
> fix(live template): Fix live template default context

- src/main/resources/fileTemplates/internal/Haskell Test Module.hs.ft
- src/main/resources/fileTemplates/internal/Haskell Test Module.hs.html
- src/main/scala/intellij/haskell/action/CreateHaskellFileAction.scala
- src/main/scala/intellij/haskell/testIntegration/CreateHaskellTestAction.scala
Closes #396.
Usual disclaimer: I don't often write Scala or Intellij plugins, I accept and appreciate any feedback to improve my code!
> feat(test): Provide SUT_NAME property to Haskell test Module

- src/main/scala/intellij/haskell/external/component/HoogleComponent.scala
Update text to reflect move of `(Re)build Hoogle Database` to the new Haskell menu
> Update notification text

- src/main/scala/intellij/haskell/action/ghci/LoadModuleAction.scala
- src/main/scala/intellij/haskell/external/component/HoogleComponent.scala
- src/main/scala/intellij/haskell/external/component/StackProjectManager.scala
- src/main/scala/intellij/haskell/external/component/package.scala
- src/main/scala/intellij/haskell/external/repl/ProjectStackRepl.scala
- src/main/scala/intellij/haskell/external/repl/StackRepl.scala
- src/main/scala/intellij/haskell/module/HaskellModuleBuilder.scala
* Some contractions for friendliness / readability (e.g. _can not_ -> _can't_)
* Some fixes for consistency in similar message 
* Fix a few typos
* Rewrite (slightly) a few of the longer / complicated ones to try to clarify the problem
Please revert any that don't work for you of course (or I can)
This closes #439.
> Fix / improve English in various user / log messages.

- build.sbt
- intellij-haskell/META-INF/plugin.xml
> fix compilation

- gen/intellij/haskell/parser/HaskellParser.java
- gen/intellij/haskell/psi/HaskellCidecl.java
- gen/intellij/haskell/psi/HaskellExpression.java
- gen/intellij/haskell/psi/HaskellQuasiQuote.java
- gen/intellij/haskell/psi/HaskellShebangLine.java
- gen/intellij/haskell/psi/HaskellTypes.java
- gen/intellij/haskell/psi/HaskellVisitor.java
- gen/intellij/haskell/psi/impl/HaskellCideclImpl.java
- gen/intellij/haskell/psi/impl/HaskellExpressionImpl.java
- gen/intellij/haskell/psi/impl/HaskellQuasiQuoteImpl.java
- gen/intellij/haskell/psi/impl/HaskellShebangLineImpl.java
- intellij-haskell/META-INF/plugin.xml
- src/main/scala/intellij/haskell/haskell.bnf
- src/main/scala/intellij/haskell/psi/HaskellQuasiQuoteElement.scala
- src/main/scala/intellij/haskell/psi/impl/HaskellQuasiQuoteElementImpl.scala
- src/main/scala/intellij/haskell/psi/impl/HaskellQuasiQuoteManipulator.scala
- src/main/scala/intellij/haskell/psi/impl/HaskellStringEscaper.java
> QuasiQuote injection, not sure if implemented correctly

- .github/FUNDING.yml
> funding: add PayPal link

- src/main/scala/intellij/haskell/util/HaskellProjectUtil.scala
An more precise implementation of #558
> improved module dir search

- intellij-haskell/META-INF/plugin.xml
- src/main/scala/intellij/haskell/annotator/HaskellAnnotator.scala
- src/main/scala/intellij/haskell/cabal/highlighting/CabalAnnotator.scala
- src/main/scala/intellij/haskell/editor/HaskellLiveTemplate.scala
- src/main/scala/intellij/haskell/external/component/FileModuleIdentifiers.scala
- src/main/scala/intellij/haskell/highlighter/HaskellHighlightingAnnotator.scala
- src/main/scala/intellij/haskell/runconfig/test/HaskellTestConfigurationFactory.scala
- regarding test config the Id has to be overridden.
- annotation methods
- live template registration
> Update a few methods for 2020.1
